import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import './styles/shared.css';
import './styles/components/navbar.css';
import './styles/components/showRow.css';
import './styles/pages/auth.css';
import './styles/pages/authLayout.css';
import './styles/pages/authBrand.css';
import './styles/pages/authForm.css';
import './styles/pages/catalog.css';
import './styles/pages/catalogHero.css';
import './styles/pages/catalogFilters.css';
import './styles/pages/watchlist.css';
import './styles/pages/profile.css';
import './styles/pages/admin.css';
import './styles/pages/manage.css';
import './styles/components/showDetailModal.css';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')).render(<App />);
